import { useEffect, useState } from "react";
import { MapPin, Search, ShieldCheck, Star, Wrench } from "lucide-react";
import api from "../../utils/axios";

export default function FindMechanics() {
  const [mechanics,setMechanics]=useState([]); const [coords,setCoords]=useState(null); const [message,setMessage]=useState("");
  useEffect(()=>{navigator.geolocation?.getCurrentPosition(p=>setCoords({lat:p.coords.latitude,lng:p.coords.longitude}),()=>setMessage("Location permission denied. You can still connect location later."))},[]);
  useEffect(()=>{if(!coords)return;api.get(`/mechanics/nearby?lat=${coords.lat}&lng=${coords.lng}`).then(r=>setMechanics(r.data.mechanics||[])).catch(()=>setMessage("Nearby mechanics could not be loaded yet."))},[coords]);

  return <div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="font-semibold text-red-600">FIND MECHANICS</p><h1 className="mt-1 text-3xl font-black">Verified help near you.</h1><p className="mt-2 text-slate-500">Only online and verified mechanics are shown by the backend.</p></div><div className="flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm shadow-sm"><MapPin size={18} className="text-red-600"/>{coords?"Location enabled":"Finding location..."}</div></div>{message&&<p className="mt-5 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{message}</p>}<div className="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{mechanics.length?mechanics.map(m=><div className="card p-5" key={m._id}><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-full bg-red-50 text-red-600"><Wrench/></div><div><h3 className="font-bold">{m.businessName||m.user?.name||"Verified Mechanic"}</h3><p className="text-xs text-slate-500">{m.serviceArea||"Nearby"}</p></div></div><div className="mt-5 flex items-center gap-4 text-sm"><span className="flex items-center gap-1"><Star size={15} className="fill-amber-400 text-amber-400"/>{m.rating||"New"}</span><span>{m.experienceYears||0} yrs exp.</span></div><div className="mt-4 flex items-center gap-2 text-xs text-green-700"><ShieldCheck size={16}/>Verified provider</div></div>):<div className="card col-span-full p-10 text-center"><Search className="mx-auto text-slate-300"/><h3 className="mt-4 font-bold">No mechanics available</h3><p className="mt-1 text-sm text-slate-500">Set a mechanic online and verified in your backend to see them here.</p></div>}</div></div>;
}