import { useEffect, useState } from "react";
import { CarFront, Pencil, Plus, Trash2 } from "lucide-react";
import api from "../../utils/axios";
import Modal from "../../Components/Modal";

export default function MyVehicles() {
  const [vehicles,setVehicles]=useState([]); const [open,setOpen]=useState(false); const [editing,setEditing]=useState(null);
  const empty={type:"car",make:"",model:"",registrationNumber:"",year:"",color:""};
  const [form,setForm]=useState(empty);
  const load=()=>api.get("/vehicles").then(r=>setVehicles(r.data.vehicles||[])).catch(()=>setVehicles([]));
  useEffect(()=>{load()},[]);
  const submit=async(e)=>{e.preventDefault(); if(editing) await api.put(`/vehicles/${editing._id}`,form); else await api.post("/vehicles",form); setOpen(false);setEditing(null);setForm(empty);load();};
  const edit=(v)=>{setEditing(v);setForm({...v});setOpen(true)};
  const remove=async(id)=>{if(confirm("Delete this vehicle?")){await api.delete(`/vehicles/${id}`);load()}};

  return <div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-3xl font-black">My Vehicles</h1><p className="mt-2 text-slate-500">Save your vehicles for faster emergency requests.</p></div><button onClick={()=>{setEditing(null);setForm(empty);setOpen(true)}} className="btn-primary"><Plus size={18}/>Add Vehicle</button></div><div className="mt-7 grid gap-4 md:grid-cols-2">{vehicles.map(v=><div key={v._id} className="card p-5"><div className="flex items-start justify-between"><div className="flex gap-4"><div className="grid h-12 w-12 place-items-center rounded-xl bg-red-50 text-red-600"><CarFront/></div><div><h3 className="font-bold">{v.make} {v.model}</h3><p className="mt-1 text-sm text-slate-500">{v.registrationNumber} • {v.type}</p></div></div><div className="flex gap-1"><button onClick={()=>edit(v)} className="rounded-lg p-2 hover:bg-slate-100"><Pencil size={16}/></button><button onClick={()=>remove(v._id)} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 size={16}/></button></div></div><div className="mt-5 grid grid-cols-3 gap-2 text-sm"><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-400">Year</span><p className="font-semibold">{v.year||"—"}</p></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-400">Color</span><p className="font-semibold">{v.color||"—"}</p></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-400">Type</span><p className="font-semibold capitalize">{v.type}</p></div></div></div>)}</div><Modal open={open} onClose={()=>setOpen(false)} title={editing?"Edit Vehicle":"Add Vehicle"}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><div><label className="label">Type</label><select className="input" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>car</option><option>bike</option><option>scooter</option><option>other</option></select></div><div><label className="label">Registration</label><input className="input" required value={form.registrationNumber} onChange={e=>setForm({...form,registrationNumber:e.target.value})}/></div><div><label className="label">Make</label><input className="input" required value={form.make} onChange={e=>setForm({...form,make:e.target.value})}/></div><div><label className="label">Model</label><input className="input" required value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></div><div><label className="label">Year</label><input className="input" type="number" value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/></div><div><label className="label">Color</label><input className="input" value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></div><button className="btn-primary sm:col-span-2">Save Vehicle</button></form></Modal></div>;
}