import { useEffect, useMemo, useState } from "react";
import { CreditCard, ReceiptIndianRupee, RefreshCw } from "lucide-react";
import api from "../../utils/axios";
const money=n=>`₹${Number(n||0).toLocaleString("en-IN")}`;
export default function Payments(){
  const [items,setItems]=useState([]); const [completed,setCompleted]=useState([]); const [message,setMessage]=useState("");
  const load=async()=>{try{const [p,r]=await Promise.all([api.get("/payments/mine"),api.get("/emergency/mine")]);setItems(p.data.payments||[]);setCompleted((r.data.requests||[]).filter(x=>x.status==="completed"&&x.mechanic))}catch(e){setMessage(e.response?.data?.message||"Could not load payments.")}};
  useEffect(()=>{load()},[]);
  const paid=useMemo(()=>items.filter(x=>x.status==="paid").reduce((s,x)=>s+Number(x.amount||0),0),[items]);
  const pending=useMemo(()=>items.filter(x=>x.status==="pending").reduce((s,x)=>s+Number(x.amount||0),0),[items]);
  const payRequest=async(req)=>{try{const existing=items.find(p=>String(p.request?._id||p.request)===String(req._id));let paymentId=existing?._id;if(!paymentId){const {data}=await api.post("/payments",{requestId:req._id,amount:req.finalAmount||req.estimatedAmount||0,method:"cash"});paymentId=data.payment?._id || data._id}await api.patch(`/payments/${paymentId}/pay`,{transactionId:`TXN-${Date.now()}`});setMessage("Payment marked as paid.");load()}catch(e){setMessage(e.response?.data?.message||"Could not process payment.")}};
  return <div className="mx-auto max-w-6xl"><div className="flex justify-between"><div><h1 className="text-3xl font-black">Payments</h1><p className="mt-2 text-slate-500">Service charges and payment records.</p></div><button onClick={load} className="btn-secondary"><RefreshCw size={16}/>Refresh</button></div>{message&&<p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm">{message}</p>}<div className="mt-7 grid gap-5 md:grid-cols-3"><div className="card p-6"><ReceiptIndianRupee className="text-red-600"/><p className="mt-5 text-sm text-slate-500">Total paid</p><p className="mt-1 text-3xl font-black">{money(paid)}</p></div><div className="card p-6"><CreditCard/><p className="mt-5 text-sm text-slate-500">Pending</p><p className="mt-1 text-3xl font-black">{money(pending)}</p></div><div className="card p-6"><p className="text-sm text-slate-500">Payment records</p><p className="mt-3 text-3xl font-black">{items.length}</p></div></div><div className="mt-7"><h2 className="text-lg font-bold">Completed services</h2><div className="mt-4 space-y-3">{completed.map(req=>{const payment=items.find(p=>String(p.request?._id||p.request)===String(req._id));return <div className="card flex flex-wrap items-center justify-between gap-4 p-5" key={req._id}><div><p className="font-bold capitalize">{req.issueType} • {req.vehicle?.make} {req.vehicle?.model}</p><p className="text-sm text-slate-500">Final amount: {money(req.finalAmount||req.estimatedAmount)}</p></div>{payment?.status==="paid"?<span className="rounded-full bg-green-50 px-3 py-1 text-xs font-semibold text-green-700">Paid</span>:<button onClick={()=>payRequest(req)} className="btn-primary">Pay {money(req.finalAmount||req.estimatedAmount)}</button>}</div>})}</div></div><div className="mt-7 space-y-3">{items.map(p=><div className="card flex justify-between p-5" key={p._id}><div><p className="font-bold">{money(p.amount)} • {p.method}</p><p className="text-sm text-slate-500">{p.status} • {new Date(p.createdAt).toLocaleString()}</p></div></div>)}</div></div>
}
