import { useEffect, useState } from "react";
import { Clock3, MapPin, Phone, Wrench, Navigation, CheckCircle2 } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import api from "../../utils/axios";
import { useSocket } from "../../context/SocketContext";

const nextStatus = { accepted:"on_the_way", on_the_way:"arrived", arrived:"repairing", repairing:"completed" };
export default function ActiveJobs() {
  const [params]=useSearchParams(); const {socket}=useSocket(); const [job,setJob]=useState(null); const [message,setMessage]=useState("");
  const requestId=params.get("requestId")||localStorage.getItem("fixmoto_active_request");
  const load=()=>requestId&&api.get(`/emergency/${requestId}`).then(r=>setJob(r.data.request)).catch(e=>setMessage(e.response?.data?.message||"Could not load job."));
  useEffect(()=>{load()},[requestId]);
  useEffect(()=>{if(!socket||!requestId)return;socket.emit("join:request",requestId);const onStatus=({requestId:id})=>{if(id===requestId)load()};socket.on("emergency:status",onStatus);return()=>socket.off("emergency:status",onStatus)},[socket,requestId]);
  const update=async(status)=>{try{const {data}=await api.patch(`/emergency/${requestId}/status`,{status});setJob(data.request);if(status==="completed")localStorage.removeItem("fixmoto_active_request")}catch(e){setMessage(e.response?.data?.message||"Could not update status.")}};
  const sendLocation=()=>{if(!navigator.geolocation||!socket||!requestId)return; navigator.geolocation.getCurrentPosition(({coords})=>socket.emit("mechanic:location",{requestId,mechanicId:job?.mechanic?._id || job?.mechanic,coordinates:[coords.longitude,coords.latitude]}),()=>setMessage("Location permission denied."))};
  if(!job)return <div className="mx-auto max-w-6xl"><h1 className="text-3xl font-black">Active Jobs</h1>{message?<p className="mt-4 text-red-600">{message}</p>:<div className="card mt-7 p-12 text-center"><Wrench className="mx-auto text-slate-300"/><p className="mt-4 font-semibold">No active job</p><p className="mt-1 text-sm text-slate-500">Accept an emergency request to start a job.</p></div>}</div>;
  const next=nextStatus[job.status];
  return <div className="mx-auto max-w-6xl"><h1 className="text-3xl font-black">Active Job</h1><p className="mt-2 text-slate-500">Update the customer as you travel and repair the vehicle.</p><div className="card mt-7 p-6"><div className="flex flex-wrap justify-between gap-4"><div><span className="rounded-full bg-red-50 px-3 py-1 text-xs font-bold capitalize text-red-700">{job.issueType}</span><h2 className="mt-3 text-xl font-black">{job.vehicle?.make} {job.vehicle?.model}</h2><p className="text-sm text-slate-500">{job.vehicle?.registrationNumber}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold capitalize">{String(job.status).replaceAll("_"," ")}</span></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Customer</p><p className="mt-1 font-bold">{job.customer?.name||"Customer"}</p><p className="text-sm text-slate-500">{job.customer?.phone||"Phone unavailable"}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Location</p><p className="mt-1 font-bold">{job.location?.address||"GPS location"}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Description</p><p className="mt-1 font-bold">{job.description||"No description"}</p></div></div><div className="mt-6 flex flex-wrap gap-3">{next&&<button onClick={()=>update(next)} className="btn-primary"><CheckCircle2 size={17}/>{next.replaceAll("_"," ")}</button>}<button onClick={sendLocation} className="btn-secondary"><Navigation size={17}/>Send My Location</button><a href={job.customer?.phone?`tel:${job.customer.phone}`:"#"} className="btn-secondary"><Phone size={17}/>Call Customer</a><span className="flex items-center gap-1 text-sm text-slate-500"><MapPin size={16}/>Live tracking connected</span></div></div></div>;
}
